notifications:
  email:
    on_success: never
    on_failure: change

env:
  DUGITE_CACHE_DIR=$HOME/.dugite/

os:
  - linux
  - osx

branches:
  only:
    - master

language: node_js
node_js:
  - "6"
  - "7"
  - "8"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.dugite/

install:
  - npm install -g npm@5.4.2
  - npm install
  - npm run build
  - npm run is-it-pretty

script:
  - TEST=1 npm test
