notifications:
  email:
    on_success: never
    on_failure: change

os:
  - linux
  - osx

branches:
  only:
    - master

language: node_js
node_js:
  - "6"
  - "7"
  - "8"

cache:
  timeout: 600
  directories:
    - node_modules

install:
  - npm install -g npm@5.5.1
  - npm install --ignore-scripts
  - npm run build
  - npm run is-it-pretty

script:
  - TEST=1 npm test
