notifications:
  email:
    on_success: never
    on_failure: change

env: DUGITE_CACHE_DIR=$HOME/.dugite/

os:
  - linux
  - osx

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js
node_js:
  - '8'
  - '10'

cache:
  timeout: 600
  directories:
    - $HOME/.dugite/
    - '$HOME/.npm'

install:
  - npm ci
  - npm run build
  - npm run is-it-pretty

script:
  - TEST=1 npm test
