notifications:
  email:
    on_success: never
    on_failure: change

os:
  - linux
  - osx
  
branches:
  only:
    - master

language: node_js
node_js:
  - "6"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install
  - npm run build

script:
  - TEST=1 npm test
