os: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "8.9.4"
    - nodejs_version: "9"
  DUGITE_CACHE_DIR: '%USERPROFILE%\.dugite\'

cache:
  - node_modules
  - '%USERPROFILE%\.dugite\'

branches:
  only:
    - master

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm@5.7.1
  - npm install
  - npm run is-it-pretty

build_script:
  - npm run build

test_script:
  - set TEST=1
  - npm test
