os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

branches:
  only:
    - master

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - set TEST=1
  - npm test
