os: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  DUGITE_CACHE_DIR: '%USERPROFILE%\.dugite\'
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'

cache:
  - '%USERPROFILE%\.dugite\'
  - '%USERPROFILE%\.npm\'

branches:
  only:
    - master
    - v2
    - /releases\/.*/

skip_tags: true

version: '{build}'

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm ci
  - npm run is-it-pretty

build_script:
  - npm run build

test_script:
  - set TEST=1
  - npm test
