name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Node ${{ matrix.node }} on ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        node: 12
        os: [macos-10.15, windows-2019, ubuntu-18.04]
        include:
          - os: macos-10.15
            friendlyName: macOS
          - os: windows-2019
            friendlyName: Windows
          - os: windows-2019
            friendlyName: Windows
            arch: x86
          - os: ubuntu-18.04
            friendlyName: Linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install and build dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run is-it-pretty
      - name: Test
        run: npm run test
        env:
          TEST: 1
